lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: 3600  # время жизни токена (секунд)

when@test:
  lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/tests/_data/private-test.pem'
    public_key: '%kernel.project_dir%/tests/_data/public-test.pem'
