name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: hidiv/php-dev:8.3.16-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cache for Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --optimize-autoloader

  test:
    name: Run Tests
    needs: build
    runs-on: hidiv/php-dev:8.3.16-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Run tests with coverage
        run: |
          vendor/bin/codecept run Unit --coverage --coverage-html --coverage-xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tests/_output/coverage/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/_output/coverage.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/_output/phpunit-report.xml
